// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: metaserver.proto

// 与 dataserver.proto 使用同一个包名，便于管理

package pb

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 节点类型枚举
type NodeType int32

const (
	NodeType_FILE      NodeType = 0
	NodeType_DIRECTORY NodeType = 1
)

// Enum value maps for NodeType.
var (
	NodeType_name = map[int32]string{
		0: "FILE",
		1: "DIRECTORY",
	}
	NodeType_value = map[string]int32{
		"FILE":      0,
		"DIRECTORY": 1,
	}
)

func (x NodeType) Enum() *NodeType {
	p := new(NodeType)
	*p = x
	return p
}

func (x NodeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeType) Descriptor() protoreflect.EnumDescriptor {
	return file_metaserver_proto_enumTypes[0].Descriptor()
}

func (NodeType) Type() protoreflect.EnumType {
	return &file_metaserver_proto_enumTypes[0]
}

func (x NodeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeType.Descriptor instead.
func (NodeType) EnumDescriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{0}
}

type Command_Action int32

const (
	Command_DELETE_BLOCK Command_Action = 0 // 删除块 (用于垃圾回收)
	Command_COPY_BLOCK   Command_Action = 1 // 复制块 (用于副本修复)
)

// Enum value maps for Command_Action.
var (
	Command_Action_name = map[int32]string{
		0: "DELETE_BLOCK",
		1: "COPY_BLOCK",
	}
	Command_Action_value = map[string]int32{
		"DELETE_BLOCK": 0,
		"COPY_BLOCK":   1,
	}
)

func (x Command_Action) Enum() *Command_Action {
	p := new(Command_Action)
	*p = x
	return p
}

func (x Command_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_metaserver_proto_enumTypes[1].Descriptor()
}

func (Command_Action) Type() protoreflect.EnumType {
	return &file_metaserver_proto_enumTypes[1]
}

func (x Command_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Action.Descriptor instead.
func (Command_Action) EnumDescriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{16, 0}
}

// 通用的简单响应，用于表示操作成功与否
type SimpleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimpleResponse) Reset() {
	*x = SimpleResponse{}
	mi := &file_metaserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimpleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleResponse) ProtoMessage() {}

func (x *SimpleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleResponse.ProtoReflect.Descriptor instead.
func (*SimpleResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// 文件或目录的核心元数据结构 (简化的 Inode)
type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inode         uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"`                         // 唯一的 inode 编号
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`                            // 完整路径
	Type          NodeType               `protobuf:"varint,3,opt,name=type,proto3,enum=dfs_project.NodeType" json:"type,omitempty"` // 类型：文件或目录
	Size          uint64                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`                           // 文件大小 (目录为0)
	ModTime       *timestamp.Timestamp   `protobuf:"bytes,5,opt,name=mod_time,json=modTime,proto3" json:"mod_time,omitempty"`       // 最后修改时间
	Replication   uint32                 `protobuf:"varint,6,opt,name=replication,proto3" json:"replication,omitempty"`             // 副本数 (比如 3)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_metaserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{1}
}

func (x *NodeInfo) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *NodeInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NodeInfo) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_FILE
}

func (x *NodeInfo) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *NodeInfo) GetModTime() *timestamp.Timestamp {
	if x != nil {
		return x.ModTime
	}
	return nil
}

func (x *NodeInfo) GetReplication() uint32 {
	if x != nil {
		return x.Replication
	}
	return 0
}

// 一个数据块的所有副本位置
type BlockLocations struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockId       uint64                 `protobuf:"varint,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	Locations     []string               `protobuf:"bytes,2,rep,name=locations,proto3" json:"locations,omitempty"` // DataServer 地址列表 (IP:Port)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockLocations) Reset() {
	*x = BlockLocations{}
	mi := &file_metaserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockLocations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockLocations) ProtoMessage() {}

func (x *BlockLocations) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockLocations.ProtoReflect.Descriptor instead.
func (*BlockLocations) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{2}
}

func (x *BlockLocations) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *BlockLocations) GetLocations() []string {
	if x != nil {
		return x.Locations
	}
	return nil
}

// CreateNode
type CreateNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Type          NodeType               `protobuf:"varint,2,opt,name=type,proto3,enum=dfs_project.NodeType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNodeRequest) Reset() {
	*x = CreateNodeRequest{}
	mi := &file_metaserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNodeRequest) ProtoMessage() {}

func (x *CreateNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNodeRequest.ProtoReflect.Descriptor instead.
func (*CreateNodeRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNodeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateNodeRequest) GetType() NodeType {
	if x != nil {
		return x.Type
	}
	return NodeType_FILE
}

// GetNodeInfo
type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_metaserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeInfoRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetNodeInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeInfo      *NodeInfo              `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_metaserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodeInfoResponse) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

// ListDirectory
type ListDirectoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryRequest) Reset() {
	*x = ListDirectoryRequest{}
	mi := &file_metaserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryRequest) ProtoMessage() {}

func (x *ListDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ListDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{6}
}

func (x *ListDirectoryRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ListDirectoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"` // 返回该目录下所有子节点的列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDirectoryResponse) Reset() {
	*x = ListDirectoryResponse{}
	mi := &file_metaserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDirectoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDirectoryResponse) ProtoMessage() {}

func (x *ListDirectoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDirectoryResponse.ProtoReflect.Descriptor instead.
func (*ListDirectoryResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{7}
}

func (x *ListDirectoryResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

// DeleteNode
type DeleteNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Recursive     bool                   `protobuf:"varint,2,opt,name=recursive,proto3" json:"recursive,omitempty"` // 是否递归删除
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNodeRequest) Reset() {
	*x = DeleteNodeRequest{}
	mi := &file_metaserver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNodeRequest) ProtoMessage() {}

func (x *DeleteNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteNodeRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteNodeRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *DeleteNodeRequest) GetRecursive() bool {
	if x != nil {
		return x.Recursive
	}
	return false
}

// GetBlockLocations
type GetBlockLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 对于写操作，Client 告诉 metaServer 文件总大小，以便规划块
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlockLocationsRequest) Reset() {
	*x = GetBlockLocationsRequest{}
	mi := &file_metaserver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockLocationsRequest) ProtoMessage() {}

func (x *GetBlockLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetBlockLocationsRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{9}
}

func (x *GetBlockLocationsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *GetBlockLocationsRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetBlockLocationsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Inode          uint64                 `protobuf:"varint,1,opt,name=inode,proto3" json:"inode,omitempty"` // 返回分配的 inode
	BlockLocations []*BlockLocations      `protobuf:"bytes,2,rep,name=block_locations,json=blockLocations,proto3" json:"block_locations,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetBlockLocationsResponse) Reset() {
	*x = GetBlockLocationsResponse{}
	mi := &file_metaserver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlockLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlockLocationsResponse) ProtoMessage() {}

func (x *GetBlockLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlockLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetBlockLocationsResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{10}
}

func (x *GetBlockLocationsResponse) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *GetBlockLocationsResponse) GetBlockLocations() []*BlockLocations {
	if x != nil {
		return x.BlockLocations
	}
	return nil
}

// FinalizeWrite
type FinalizeWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Inode         uint64                 `protobuf:"varint,2,opt,name=inode,proto3" json:"inode,omitempty"`
	Size          uint64                 `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeWriteRequest) Reset() {
	*x = FinalizeWriteRequest{}
	mi := &file_metaserver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeWriteRequest) ProtoMessage() {}

func (x *FinalizeWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeWriteRequest.ProtoReflect.Descriptor instead.
func (*FinalizeWriteRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{11}
}

func (x *FinalizeWriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FinalizeWriteRequest) GetInode() uint64 {
	if x != nil {
		return x.Inode
	}
	return 0
}

func (x *FinalizeWriteRequest) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

// GetClusterInfo
type DataServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	BlockCount    uint64                 `protobuf:"varint,3,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	FreeSpace     uint64                 `protobuf:"varint,4,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataServerInfo) Reset() {
	*x = DataServerInfo{}
	mi := &file_metaserver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataServerInfo) ProtoMessage() {}

func (x *DataServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataServerInfo.ProtoReflect.Descriptor instead.
func (*DataServerInfo) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{12}
}

func (x *DataServerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataServerInfo) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *DataServerInfo) GetBlockCount() uint64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *DataServerInfo) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

type GetClusterInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoRequest) Reset() {
	*x = GetClusterInfoRequest{}
	mi := &file_metaserver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoRequest) ProtoMessage() {}

func (x *GetClusterInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoRequest.ProtoReflect.Descriptor instead.
func (*GetClusterInfoRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{13}
}

type GetClusterInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataservers   []*DataServerInfo      `protobuf:"bytes,1,rep,name=dataservers,proto3" json:"dataservers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInfoResponse) Reset() {
	*x = GetClusterInfoResponse{}
	mi := &file_metaserver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInfoResponse) ProtoMessage() {}

func (x *GetClusterInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInfoResponse.ProtoReflect.Descriptor instead.
func (*GetClusterInfoResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{14}
}

func (x *GetClusterInfoResponse) GetDataservers() []*DataServerInfo {
	if x != nil {
		return x.Dataservers
	}
	return nil
}

// Heartbeat
type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DataserverId   string                 `protobuf:"bytes,1,opt,name=dataserver_id,json=dataserverId,proto3" json:"dataserver_id,omitempty"`
	DataserverAddr string                 `protobuf:"bytes,2,opt,name=dataserver_addr,json=dataserverAddr,proto3" json:"dataserver_addr,omitempty"`
	BlockCount     uint64                 `protobuf:"varint,3,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	FreeSpace      uint64                 `protobuf:"varint,4,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"`
	BlockIdsReport []uint64               `protobuf:"varint,5,rep,packed,name=block_ids_report,json=blockIdsReport,proto3" json:"block_ids_report,omitempty"` // 完整的块报告
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_metaserver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{15}
}

func (x *HeartbeatRequest) GetDataserverId() string {
	if x != nil {
		return x.DataserverId
	}
	return ""
}

func (x *HeartbeatRequest) GetDataserverAddr() string {
	if x != nil {
		return x.DataserverAddr
	}
	return ""
}

func (x *HeartbeatRequest) GetBlockCount() uint64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *HeartbeatRequest) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

func (x *HeartbeatRequest) GetBlockIdsReport() []uint64 {
	if x != nil {
		return x.BlockIdsReport
	}
	return nil
}

// 心跳响应可以携带来自 metaServer 的指令
type Command struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Action  Command_Action         `protobuf:"varint,1,opt,name=action,proto3,enum=dfs_project.Command_Action" json:"action,omitempty"`
	BlockId uint64                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// 对于 COPY_BLOCK，这里是源地址
	// 对于其他指令，可以为空
	Targets       []string `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_metaserver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{16}
}

func (x *Command) GetAction() Command_Action {
	if x != nil {
		return x.Action
	}
	return Command_DELETE_BLOCK
}

func (x *Command) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *Command) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_metaserver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{17}
}

func (x *HeartbeatResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

// SyncWAL (用于主从同步)
type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // 序列化后的操作指令
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_metaserver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{18}
}

func (x *LogEntry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_metaserver_proto protoreflect.FileDescriptor

const file_metaserver_proto_rawDesc = "" +
	"\n" +
	"\x10metaserver.proto\x12\vdfs_project\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x0eSimpleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xcc\x01\n" +
	"\bNodeInfo\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12)\n" +
	"\x04type\x18\x03 \x01(\x0e2\x15.dfs_project.NodeTypeR\x04type\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x04R\x04size\x125\n" +
	"\bmod_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\amodTime\x12 \n" +
	"\vreplication\x18\x06 \x01(\rR\vreplication\"I\n" +
	"\x0eBlockLocations\x12\x19\n" +
	"\bblock_id\x18\x01 \x01(\x04R\ablockId\x12\x1c\n" +
	"\tlocations\x18\x02 \x03(\tR\tlocations\"R\n" +
	"\x11CreateNodeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12)\n" +
	"\x04type\x18\x02 \x01(\x0e2\x15.dfs_project.NodeTypeR\x04type\"(\n" +
	"\x12GetNodeInfoRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"I\n" +
	"\x13GetNodeInfoResponse\x122\n" +
	"\tnode_info\x18\x01 \x01(\v2\x15.dfs_project.NodeInfoR\bnodeInfo\"*\n" +
	"\x14ListDirectoryRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"D\n" +
	"\x15ListDirectoryResponse\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.dfs_project.NodeInfoR\x05nodes\"E\n" +
	"\x11DeleteNodeRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\trecursive\x18\x02 \x01(\bR\trecursive\"B\n" +
	"\x18GetBlockLocationsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"w\n" +
	"\x19GetBlockLocationsResponse\x12\x14\n" +
	"\x05inode\x18\x01 \x01(\x04R\x05inode\x12D\n" +
	"\x0fblock_locations\x18\x02 \x03(\v2\x1b.dfs_project.BlockLocationsR\x0eblockLocations\"T\n" +
	"\x14FinalizeWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05inode\x18\x02 \x01(\x04R\x05inode\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x04R\x04size\"t\n" +
	"\x0eDataServerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x12\x1f\n" +
	"\vblock_count\x18\x03 \x01(\x04R\n" +
	"blockCount\x12\x1d\n" +
	"\n" +
	"free_space\x18\x04 \x01(\x04R\tfreeSpace\"\x17\n" +
	"\x15GetClusterInfoRequest\"W\n" +
	"\x16GetClusterInfoResponse\x12=\n" +
	"\vdataservers\x18\x01 \x03(\v2\x1b.dfs_project.DataServerInfoR\vdataservers\"\xca\x01\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\rdataserver_id\x18\x01 \x01(\tR\fdataserverId\x12'\n" +
	"\x0fdataserver_addr\x18\x02 \x01(\tR\x0edataserverAddr\x12\x1f\n" +
	"\vblock_count\x18\x03 \x01(\x04R\n" +
	"blockCount\x12\x1d\n" +
	"\n" +
	"free_space\x18\x04 \x01(\x04R\tfreeSpace\x12(\n" +
	"\x10block_ids_report\x18\x05 \x03(\x04R\x0eblockIdsReport\"\x9f\x01\n" +
	"\aCommand\x123\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1b.dfs_project.Command.ActionR\x06action\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\x04R\ablockId\x12\x18\n" +
	"\atargets\x18\x03 \x03(\tR\atargets\"*\n" +
	"\x06Action\x12\x10\n" +
	"\fDELETE_BLOCK\x10\x00\x12\x0e\n" +
	"\n" +
	"COPY_BLOCK\x10\x01\"E\n" +
	"\x11HeartbeatResponse\x120\n" +
	"\bcommands\x18\x01 \x03(\v2\x14.dfs_project.CommandR\bcommands\"\x1e\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data*#\n" +
	"\bNodeType\x12\b\n" +
	"\x04FILE\x10\x00\x12\r\n" +
	"\tDIRECTORY\x10\x012\xf0\x05\n" +
	"\x11MetaServerService\x12I\n" +
	"\n" +
	"CreateNode\x12\x1e.dfs_project.CreateNodeRequest\x1a\x1b.dfs_project.SimpleResponse\x12P\n" +
	"\vGetNodeInfo\x12\x1f.dfs_project.GetNodeInfoRequest\x1a .dfs_project.GetNodeInfoResponse\x12V\n" +
	"\rListDirectory\x12!.dfs_project.ListDirectoryRequest\x1a\".dfs_project.ListDirectoryResponse\x12I\n" +
	"\n" +
	"DeleteNode\x12\x1e.dfs_project.DeleteNodeRequest\x1a\x1b.dfs_project.SimpleResponse\x12b\n" +
	"\x11GetBlockLocations\x12%.dfs_project.GetBlockLocationsRequest\x1a&.dfs_project.GetBlockLocationsResponse\x12O\n" +
	"\rFinalizeWrite\x12!.dfs_project.FinalizeWriteRequest\x1a\x1b.dfs_project.SimpleResponse\x12Y\n" +
	"\x0eGetClusterInfo\x12\".dfs_project.GetClusterInfoRequest\x1a#.dfs_project.GetClusterInfoResponse\x12J\n" +
	"\tHeartbeat\x12\x1d.dfs_project.HeartbeatRequest\x1a\x1e.dfs_project.HeartbeatResponse\x12?\n" +
	"\aSyncWAL\x12\x15.dfs_project.LogEntry\x1a\x1b.dfs_project.SimpleResponse(\x01B\x06Z\x04./pbb\x06proto3"

var (
	file_metaserver_proto_rawDescOnce sync.Once
	file_metaserver_proto_rawDescData []byte
)

func file_metaserver_proto_rawDescGZIP() []byte {
	file_metaserver_proto_rawDescOnce.Do(func() {
		file_metaserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metaserver_proto_rawDesc), len(file_metaserver_proto_rawDesc)))
	})
	return file_metaserver_proto_rawDescData
}

var file_metaserver_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_metaserver_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_metaserver_proto_goTypes = []any{
	(NodeType)(0),                     // 0: dfs_project.NodeType
	(Command_Action)(0),               // 1: dfs_project.Command.Action
	(*SimpleResponse)(nil),            // 2: dfs_project.SimpleResponse
	(*NodeInfo)(nil),                  // 3: dfs_project.NodeInfo
	(*BlockLocations)(nil),            // 4: dfs_project.BlockLocations
	(*CreateNodeRequest)(nil),         // 5: dfs_project.CreateNodeRequest
	(*GetNodeInfoRequest)(nil),        // 6: dfs_project.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),       // 7: dfs_project.GetNodeInfoResponse
	(*ListDirectoryRequest)(nil),      // 8: dfs_project.ListDirectoryRequest
	(*ListDirectoryResponse)(nil),     // 9: dfs_project.ListDirectoryResponse
	(*DeleteNodeRequest)(nil),         // 10: dfs_project.DeleteNodeRequest
	(*GetBlockLocationsRequest)(nil),  // 11: dfs_project.GetBlockLocationsRequest
	(*GetBlockLocationsResponse)(nil), // 12: dfs_project.GetBlockLocationsResponse
	(*FinalizeWriteRequest)(nil),      // 13: dfs_project.FinalizeWriteRequest
	(*DataServerInfo)(nil),            // 14: dfs_project.DataServerInfo
	(*GetClusterInfoRequest)(nil),     // 15: dfs_project.GetClusterInfoRequest
	(*GetClusterInfoResponse)(nil),    // 16: dfs_project.GetClusterInfoResponse
	(*HeartbeatRequest)(nil),          // 17: dfs_project.HeartbeatRequest
	(*Command)(nil),                   // 18: dfs_project.Command
	(*HeartbeatResponse)(nil),         // 19: dfs_project.HeartbeatResponse
	(*LogEntry)(nil),                  // 20: dfs_project.LogEntry
	(*timestamp.Timestamp)(nil),       // 21: google.protobuf.Timestamp
}
var file_metaserver_proto_depIdxs = []int32{
	0,  // 0: dfs_project.NodeInfo.type:type_name -> dfs_project.NodeType
	21, // 1: dfs_project.NodeInfo.mod_time:type_name -> google.protobuf.Timestamp
	0,  // 2: dfs_project.CreateNodeRequest.type:type_name -> dfs_project.NodeType
	3,  // 3: dfs_project.GetNodeInfoResponse.node_info:type_name -> dfs_project.NodeInfo
	3,  // 4: dfs_project.ListDirectoryResponse.nodes:type_name -> dfs_project.NodeInfo
	4,  // 5: dfs_project.GetBlockLocationsResponse.block_locations:type_name -> dfs_project.BlockLocations
	14, // 6: dfs_project.GetClusterInfoResponse.dataservers:type_name -> dfs_project.DataServerInfo
	1,  // 7: dfs_project.Command.action:type_name -> dfs_project.Command.Action
	18, // 8: dfs_project.HeartbeatResponse.commands:type_name -> dfs_project.Command
	5,  // 9: dfs_project.MetaServerService.CreateNode:input_type -> dfs_project.CreateNodeRequest
	6,  // 10: dfs_project.MetaServerService.GetNodeInfo:input_type -> dfs_project.GetNodeInfoRequest
	8,  // 11: dfs_project.MetaServerService.ListDirectory:input_type -> dfs_project.ListDirectoryRequest
	10, // 12: dfs_project.MetaServerService.DeleteNode:input_type -> dfs_project.DeleteNodeRequest
	11, // 13: dfs_project.MetaServerService.GetBlockLocations:input_type -> dfs_project.GetBlockLocationsRequest
	13, // 14: dfs_project.MetaServerService.FinalizeWrite:input_type -> dfs_project.FinalizeWriteRequest
	15, // 15: dfs_project.MetaServerService.GetClusterInfo:input_type -> dfs_project.GetClusterInfoRequest
	17, // 16: dfs_project.MetaServerService.Heartbeat:input_type -> dfs_project.HeartbeatRequest
	20, // 17: dfs_project.MetaServerService.SyncWAL:input_type -> dfs_project.LogEntry
	2,  // 18: dfs_project.MetaServerService.CreateNode:output_type -> dfs_project.SimpleResponse
	7,  // 19: dfs_project.MetaServerService.GetNodeInfo:output_type -> dfs_project.GetNodeInfoResponse
	9,  // 20: dfs_project.MetaServerService.ListDirectory:output_type -> dfs_project.ListDirectoryResponse
	2,  // 21: dfs_project.MetaServerService.DeleteNode:output_type -> dfs_project.SimpleResponse
	12, // 22: dfs_project.MetaServerService.GetBlockLocations:output_type -> dfs_project.GetBlockLocationsResponse
	2,  // 23: dfs_project.MetaServerService.FinalizeWrite:output_type -> dfs_project.SimpleResponse
	16, // 24: dfs_project.MetaServerService.GetClusterInfo:output_type -> dfs_project.GetClusterInfoResponse
	19, // 25: dfs_project.MetaServerService.Heartbeat:output_type -> dfs_project.HeartbeatResponse
	2,  // 26: dfs_project.MetaServerService.SyncWAL:output_type -> dfs_project.SimpleResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_metaserver_proto_init() }
func file_metaserver_proto_init() {
	if File_metaserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metaserver_proto_rawDesc), len(file_metaserver_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metaserver_proto_goTypes,
		DependencyIndexes: file_metaserver_proto_depIdxs,
		EnumInfos:         file_metaserver_proto_enumTypes,
		MessageInfos:      file_metaserver_proto_msgTypes,
	}.Build()
	File_metaserver_proto = out.File
	file_metaserver_proto_goTypes = nil
	file_metaserver_proto_depIdxs = nil
}
