// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: metaserver.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Command_Action int32

const (
	Command_DELETE_BLOCK Command_Action = 0 // 删除块 (用于垃圾回收)
	Command_COPY_BLOCK   Command_Action = 1 // 复制块 (用于副本修复)
)

// Enum value maps for Command_Action.
var (
	Command_Action_name = map[int32]string{
		0: "DELETE_BLOCK",
		1: "COPY_BLOCK",
	}
	Command_Action_value = map[string]int32{
		"DELETE_BLOCK": 0,
		"COPY_BLOCK":   1,
	}
)

func (x Command_Action) Enum() *Command_Action {
	p := new(Command_Action)
	*p = x
	return p
}

func (x Command_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Command_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_metaserver_proto_enumTypes[0].Descriptor()
}

func (Command_Action) Type() protoreflect.EnumType {
	return &file_metaserver_proto_enumTypes[0]
}

func (x Command_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Command_Action.Descriptor instead.
func (Command_Action) EnumDescriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{1, 0}
}

type HeartbeatRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DataserverId   string                 `protobuf:"bytes,1,opt,name=dataserver_id,json=dataserverId,proto3" json:"dataserver_id,omitempty"`
	DataserverAddr string                 `protobuf:"bytes,2,opt,name=dataserver_addr,json=dataserverAddr,proto3" json:"dataserver_addr,omitempty"`
	BlockCount     uint64                 `protobuf:"varint,3,opt,name=block_count,json=blockCount,proto3" json:"block_count,omitempty"`
	FreeSpace      uint64                 `protobuf:"varint,4,opt,name=free_space,json=freeSpace,proto3" json:"free_space,omitempty"`
	BlockIdsReport []uint64               `protobuf:"varint,5,rep,packed,name=block_ids_report,json=blockIdsReport,proto3" json:"block_ids_report,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_metaserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{0}
}

func (x *HeartbeatRequest) GetDataserverId() string {
	if x != nil {
		return x.DataserverId
	}
	return ""
}

func (x *HeartbeatRequest) GetDataserverAddr() string {
	if x != nil {
		return x.DataserverAddr
	}
	return ""
}

func (x *HeartbeatRequest) GetBlockCount() uint64 {
	if x != nil {
		return x.BlockCount
	}
	return 0
}

func (x *HeartbeatRequest) GetFreeSpace() uint64 {
	if x != nil {
		return x.FreeSpace
	}
	return 0
}

func (x *HeartbeatRequest) GetBlockIdsReport() []uint64 {
	if x != nil {
		return x.BlockIdsReport
	}
	return nil
}

type Command struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Action  Command_Action         `protobuf:"varint,1,opt,name=action,proto3,enum=dfs_project.Command_Action" json:"action,omitempty"`
	BlockId uint64                 `protobuf:"varint,2,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// 对于 COPY_BLOCK，这里是源地址
	// 对于其他指令，可以为空
	Targets       []string `protobuf:"bytes,3,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_metaserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetAction() Command_Action {
	if x != nil {
		return x.Action
	}
	return Command_DELETE_BLOCK
}

func (x *Command) GetBlockId() uint64 {
	if x != nil {
		return x.BlockId
	}
	return 0
}

func (x *Command) GetTargets() []string {
	if x != nil {
		return x.Targets
	}
	return nil
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*Command             `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_metaserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metaserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_metaserver_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatResponse) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

var File_metaserver_proto protoreflect.FileDescriptor

const file_metaserver_proto_rawDesc = "" +
	"\n" +
	"\x10metaserver.proto\x12\vdfs_project\"\xca\x01\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\rdataserver_id\x18\x01 \x01(\tR\fdataserverId\x12'\n" +
	"\x0fdataserver_addr\x18\x02 \x01(\tR\x0edataserverAddr\x12\x1f\n" +
	"\vblock_count\x18\x03 \x01(\x04R\n" +
	"blockCount\x12\x1d\n" +
	"\n" +
	"free_space\x18\x04 \x01(\x04R\tfreeSpace\x12(\n" +
	"\x10block_ids_report\x18\x05 \x03(\x04R\x0eblockIdsReport\"\x9f\x01\n" +
	"\aCommand\x123\n" +
	"\x06action\x18\x01 \x01(\x0e2\x1b.dfs_project.Command.ActionR\x06action\x12\x19\n" +
	"\bblock_id\x18\x02 \x01(\x04R\ablockId\x12\x18\n" +
	"\atargets\x18\x03 \x03(\tR\atargets\"*\n" +
	"\x06Action\x12\x10\n" +
	"\fDELETE_BLOCK\x10\x00\x12\x0e\n" +
	"\n" +
	"COPY_BLOCK\x10\x01\"E\n" +
	"\x11HeartbeatResponse\x120\n" +
	"\bcommands\x18\x01 \x03(\v2\x14.dfs_project.CommandR\bcommands2_\n" +
	"\x11MetaServerService\x12J\n" +
	"\tHeartbeat\x12\x1d.dfs_project.HeartbeatRequest\x1a\x1e.dfs_project.HeartbeatResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_metaserver_proto_rawDescOnce sync.Once
	file_metaserver_proto_rawDescData []byte
)

func file_metaserver_proto_rawDescGZIP() []byte {
	file_metaserver_proto_rawDescOnce.Do(func() {
		file_metaserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metaserver_proto_rawDesc), len(file_metaserver_proto_rawDesc)))
	})
	return file_metaserver_proto_rawDescData
}

var file_metaserver_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_metaserver_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_metaserver_proto_goTypes = []any{
	(Command_Action)(0),       // 0: dfs_project.Command.Action
	(*HeartbeatRequest)(nil),  // 1: dfs_project.HeartbeatRequest
	(*Command)(nil),           // 2: dfs_project.Command
	(*HeartbeatResponse)(nil), // 3: dfs_project.HeartbeatResponse
}
var file_metaserver_proto_depIdxs = []int32{
	0, // 0: dfs_project.Command.action:type_name -> dfs_project.Command.Action
	2, // 1: dfs_project.HeartbeatResponse.commands:type_name -> dfs_project.Command
	1, // 2: dfs_project.MetaServerService.Heartbeat:input_type -> dfs_project.HeartbeatRequest
	3, // 3: dfs_project.MetaServerService.Heartbeat:output_type -> dfs_project.HeartbeatResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metaserver_proto_init() }
func file_metaserver_proto_init() {
	if File_metaserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metaserver_proto_rawDesc), len(file_metaserver_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metaserver_proto_goTypes,
		DependencyIndexes: file_metaserver_proto_depIdxs,
		EnumInfos:         file_metaserver_proto_enumTypes,
		MessageInfos:      file_metaserver_proto_msgTypes,
	}.Build()
	File_metaserver_proto = out.File
	file_metaserver_proto_goTypes = nil
	file_metaserver_proto_depIdxs = nil
}
